// Shared property-based test harness for gh-142 — data-quality invariant tests
// over the pure token-tracking / analysis functions.
//
// This file provides the fast-check building blocks (run-count config +
// arbitraries) that the property test files (T1.2 token-tracker, T1.3
// agent-efficiency) consume. It deliberately contains NO test cases of its own.
//
// Run count: the standard suite uses a fast default (PROPERTY_RUNS = 100) so a
// plain `npm test` stays quick. A nightly job can bump the number of generated
// cases by setting the PROPERTY_TEST_RUNS env var (e.g. PROPERTY_TEST_RUNS=1000)
// — it is parsed as an integer and only used when it is a positive number;
// anything unset / invalid / non-positive falls back to the default.

import fc from 'fast-check';
import type { TranscriptMessage, UsageInfo, TokenDataPoint } from '../../src/shared/types.js';

// ── Run-count configuration ─────────────────────────────────────────

/** Fast default so the standard suite stays quick. */
const DEFAULT_PROPERTY_RUNS = 100;

/**
 * Number of generated cases per property. Derived from the
 * `PROPERTY_TEST_RUNS` env var (bumped by the nightly job); falls back to
 * {@link DEFAULT_PROPERTY_RUNS} when the var is unset, non-numeric, or not a
 * positive integer.
 */
export const PROPERTY_RUNS: number = (() => {
  const raw = process.env.PROPERTY_TEST_RUNS;
  if (raw === undefined) return DEFAULT_PROPERTY_RUNS;
  const parsed = Number.parseInt(raw, 10);
  return Number.isFinite(parsed) && parsed > 0 ? parsed : DEFAULT_PROPERTY_RUNS;
})();

/**
 * fast-check {@link fc.Parameters} for `fc.assert`. Only the run count is set;
 * no explicit seed, so fast-check picks its own each run and explores different
 * cases over time (a failing case prints the seed to reproduce). Set a `seed`
 * here if a run ever needs to be deterministic.
 */
export function fcParams(): fc.Parameters<unknown> {
  return { numRuns: PROPERTY_RUNS };
}

// ── Shared bounds / helpers ─────────────────────────────────────────

// Upper bound wide enough to include realistic-and-then-some token counts,
// including values that overflow a model's context window.
const MAX_TOKENS = 2_000_000;

const tokenCount = fc.integer({ min: 0, max: MAX_TOKENS });

// Deterministic ISO timestamp for array index `i` (base epoch + i*1000ms), so
// arrays generated by index have strictly ascending timestamps.
const BASE_EPOCH_MS = Date.parse('2026-01-01T00:00:00.000Z');
function timestampForIndex(i: number): string {
  return new Date(BASE_EPOCH_MS + i * 1000).toISOString();
}

// Small model pool including a sonnet, an opus, and `undefined` (unset model).
const MODEL_POOL = ['claude-sonnet-4-6', 'claude-opus-4-6', undefined] as const;

// ── Arbitraries: usage / transcript messages ────────────────────────

/**
 * A non-negative {@link UsageInfo}. The 5m / 1h cache-creation sub-buckets are
 * generated first, then `cache_creation_input_tokens` is set to their sum so the
 * sub-buckets partition the combined cache write (models real transcript data:
 * `cache_creation_5m + cache_creation_1h === cache_creation`).
 */
export const usageArb: fc.Arbitrary<UsageInfo> = fc
  .record({
    input_tokens: tokenCount,
    output_tokens: tokenCount,
    cache_read_input_tokens: tokenCount,
    cache_creation_5m_input_tokens: tokenCount,
    cache_creation_1h_input_tokens: tokenCount,
  })
  .map((u) => ({
    ...u,
    cache_creation_input_tokens:
      u.cache_creation_5m_input_tokens + u.cache_creation_1h_input_tokens,
  }));

/**
 * An assistant {@link TranscriptMessage} for position `index`. Timestamp is
 * derived deterministically from `index` so message arrays stay time-ordered;
 * the model is drawn from a small pool including a sonnet, an opus, and unset.
 */
export function assistantMsgArb(index: number): fc.Arbitrary<TranscriptMessage> {
  return fc
    .record({
      usage: usageArb,
      model: fc.constantFrom(...MODEL_POOL),
    })
    .map(({ usage, model }) => {
      const msg: TranscriptMessage = {
        uuid: `uuid-${index}`,
        parentUuid: null,
        type: 'assistant',
        timestamp: timestampForIndex(index),
        content: [{ type: 'text', text: 'response' }],
        usage,
      };
      if (model !== undefined) msg.model = model;
      return msg;
    });
}

/**
 * An array (length ~0..40) of assistant messages with strictly ascending
 * timestamps — the timestamp is assigned by array index so ordering is
 * well-defined regardless of the generated usage values.
 */
export const transcriptArb: fc.Arbitrary<TranscriptMessage[]> = fc
  .array(usageArb, { minLength: 0, maxLength: 40 })
  .chain((usages) =>
    fc
      .array(fc.constantFrom(...MODEL_POOL), {
        minLength: usages.length,
        maxLength: usages.length,
      })
      .map((models) =>
        usages.map((usage, i) => {
          const msg: TranscriptMessage = {
            uuid: `uuid-${i}`,
            parentUuid: null,
            type: 'assistant',
            timestamp: timestampForIndex(i),
            content: [{ type: 'text', text: 'response' }],
            usage,
          };
          const model = models[i];
          if (model !== undefined) msg.model = model;
          return msg;
        }),
      ),
  );

// ── Arbitraries: session / agent token timelines ────────────────────

/** A single non-negative {@link TokenDataPoint} for timeline position `i`. */
function tokenDataPointArb(i: number): fc.Arbitrary<TokenDataPoint> {
  return fc
    .record({
      input_tokens: tokenCount,
      output_tokens: tokenCount,
      cache_read_tokens: tokenCount,
      cache_write_tokens: tokenCount,
      context_pct: fc.double({ min: 0, max: 100, noNaN: true }),
      is_compaction: fc.boolean(),
    })
    .map((p) => ({
      timestamp: timestampForIndex(i),
      input_tokens: p.input_tokens,
      output_tokens: p.output_tokens,
      cache_read_tokens: p.cache_read_tokens,
      cache_write_tokens: p.cache_write_tokens,
      context_pct: p.context_pct,
      event_type: 'assistant_message',
      is_compaction: p.is_compaction,
    }));
}

/**
 * A session token timeline: non-negative token fields, ascending timestamps by
 * index. `context_pct` / `is_compaction` are simple/derived and are not
 * asserted by the invariant that compares child peak ≤ session peak.
 */
export const timelineArb: fc.Arbitrary<TokenDataPoint[]> = fc
  .integer({ min: 0, max: 40 })
  .chain((len) =>
    fc.tuple(...Array.from({ length: len }, (_unused, i) => tokenDataPointArb(i))),
  );

/**
 * A session timeline paired with an agent sub-timeline drawn as a subarray of
 * the session points. This is the convenient shape for T1.3: because the agent
 * points are a subset of the session points, any peak taken over the agent
 * timeline is ≤ the peak over the session timeline.
 */
export const sessionAndAgentTimelineArb: fc.Arbitrary<{
  session: TokenDataPoint[];
  agent: TokenDataPoint[];
}> = timelineArb.chain((session) =>
  fc.subarray(session).map((agent) => ({ session, agent })),
);
